name: dispatch_sender
on:
  push:
    branches:
      - main
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      tag-name: ${{  steps.generate_tag.outputs.tag-name  }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate tag
      id: generate_tag
      run: echo "tag-name=test-${{ github.sha }}" >> "$GITHUB_OUTPUT"
      
  dispatch:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:  
    - name: Notify deploy repo
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.DEPLOY_PAT }}
        repository: Carlinhos2912/repo-dispatch-test-reciever
        event-type: image-published
        client-payload: |
          {
            "image": "myapp",
            "tag": "${{  needs.build.outputs.tag-name  }}",
            "environment": "preview"
          }

    
  
